version: "3.8"
services:
  nacos:
    image: 032274069722.dkr.ecr.eu-west-1.amazonaws.com/techops/nacos
    build:
      context: .
      args:
        <<: &labels
          VERSION: v2.0.3
      labels:
        <<: *labels
    ports:
      - "8851:8848"
